pipelines:
  - name: art_pipeline_hello_world
    configuration:
      environmentVariables:
        readOnly:
          MY_MESSAGE: '"Hello World!"'
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: myAppRepo
        execution:
          onExecute:
            - echo $MY_MESSAGE
            - echo "running CI for master"
resources:
  - name: art_hello_world
    type: GitRepo
    configuration:
      gitProvider: arturo_github
      path: hello-world/hello-world-all-in-one.yaml
