pipelines:
  - name: art_pipeline_hello_world
    configuration:
      environmentVariables:
        readOnly:
          MY_MESSAGE: '"Hello World 1.0!"'
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: art_hello_world
        execution:
          onExecute:
            - echo $MY_MESSAGE
            - echo "running CI for master"
resources:
  - name: art_hello_world
    type: GitRepo
    configuration:
      gitProvider: arturo_github
      path: jfrog-aparicio/jfrog-pipelines-example
